---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(broom)
```

```{r}
df <- read_csv("gfp_regression_speed.csv")
df
```

```{r, fig.height=3, fig.width=9}
df %>% filter(charging_rate %in% c(30, 100, 300, 1000, 3000), speed == 0.5) %>%
  ggplot(aes(GFP, cellularProtein_norm, color = factor(codon))) +
    geom_point(size=1.5) + 
    geom_line() +
    #geom_line() +
    #geom_smooth(method = "lm", se = FALSE, formula = y ~ x + 1, fullrange=TRUE) +
    facet_wrap(~charging_rate, ncol=5) +
    xlab("transgene expression") +
    ylab("norm e.coli expression") +
    scale_y_continuous(limits = c(0.8, 1)) +
    scale_x_continuous(breaks= c(1000 , 5000)) +
    #scale_x_continuous(limits=c(0, 10000)) + scale_y_continuous(limits=c(0.8, 1.0)) +
    scale_color_discrete_sequential(name="transgene pref.\ncodon use (%)", palette = "viridis") +
    theme_bw() +
    theme(legend.position = "bottom")
```



```{r}
library(tidyverse)
library(broom)

df <- read_csv("gfp_regression_speed.csv")
df

df %>% filter(charging_rate < 10000) %>%
  ggplot(aes(GFP, cellularProtein_norm, color = factor(codon))) +
    geom_point() + 
    geom_smooth(method = "lm", se = FALSE, formula = y ~ x + 1, fullrange=TRUE) +
    facet_grid(cols = vars(charging_rate), rows = vars(speed)) +
    xlab("transgene expression") +
    ylab("norm e.coli expression") +
    scale_y_continuous(limits = c(0, 1)) +
    scale_x_continuous(breaks= c(5000 , 15000)) +
    #scale_x_continuous(limits=c(0, 10000)) + scale_y_continuous(limits=c(0.8, 1.0)) +
    scale_color_discrete_sequential(name="transgene \npref. codon\nuse (%)", palette = "viridis") +
    theme_bw()
```

```{r}
df %>% 
  filter(charging_rate %in% c(10, 100, 1000)) %>%
  filter(gfp_rbs_foldx %in% c(3.0, 10.0, 30.0), speed==1) %>%
  group_by(charging_rate, gfp_rbs_foldx) %>%
  mutate(GFP_norm = GFP/ max(GFP)) %>%
  ggplot(aes(x = factor(codon), y = GFP_norm)) +
    geom_point(color="#4BABED", size=2) +
    scale_y_continuous(limits=c(0.6, 1.0)) +
    facet_grid(rows=vars(charging_rate), cols=vars(gfp_rbs_foldx)) +
    theme_bw()
```


```{r}
models <- df %>%
#    filter(codon != 0.5) %>%
    group_by(charging_rate, speed) %>%
    do(tidy(lm(data = ., formula = cellularProtein_norm ~ factor(codon):GFP)))
models
```

```{r}
models %>%
  filter(term != "(Intercept)") %>% 
  mutate(term = recode(term, `factor(codon)0.1:GFP` = 0.1,
                       `factor(codon)0.3:GFP` = 0.3,
                       `factor(codon)0.5:GFP` = 0.5,
                       `factor(codon)0.7:GFP` = 0.7,
                       `factor(codon)0.9:GFP` = 0.9)) %>%
  group_by(speed) %>%
  mutate(estimate = estimate*-1) %>%
  ungroup() %>%
  ggplot(aes(term, estimate, color=as.factor(charging_rate))) +
  facet_wrap(~speed) +
  geom_point(size=3) +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_discrete_sequential(palette="SunsetDark", name="charging rate") +
  scale_x_continuous(name="transgene pref. codon use",
                     breaks=c(0.1, 0.3, 0.5, 0.7, 0.9)) +
  scale_y_continuous(name="change e.coli expression") +
  theme_bw()
```
```{r, fig.width=7, fig.height=4}
models %>%
  filter(term != "(Intercept)") %>% 
  mutate(term = recode(term, `factor(codon)0.1:GFP` = 0.1,
                       `factor(codon)0.3:GFP` = 0.3,
                       `factor(codon)0.5:GFP` = 0.5,
                       `factor(codon)0.7:GFP` = 0.7,
                       `factor(codon)0.9:GFP` = 0.9)) %>%
  filter(speed == 2) %>%
  mutate(estimate = estimate*-1) %>%
  ungroup() %>%
  ggplot(aes(term, estimate, color=as.factor(charging_rate))) +
  #facet_wrap(~speed) +
  geom_point(size=3) +
  geom_smooth(method = "lm", se = FALSE, formula = y ~ x) +
  scale_color_discrete_sequential(palette="SunsetDark", name="charging rate") +
  scale_x_continuous(name="transgene pref. codon use",
                     breaks=c(0.1, 0.3, 0.5, 0.7, 0.9)) +
  scale_y_continuous(name="change e.coli expression") +
  theme_bw()
```


```{r}
coef <- models %>%
  filter(term != "(Intercept)") %>% 
  mutate(term = recode(term, `factor(codon)0.1:GFP` = 0.1,
                       `factor(codon)0.3:GFP` = 0.3,
                       `factor(codon)0.5:GFP` = 0.5,
                       `factor(codon)0.7:GFP` = 0.7,
                       `factor(codon)0.9:GFP` = 0.9)) %>%
  group_by(charging_rate, speed) %>%
  do(tidy(lm(data = ., formula = estimate ~ term))) %>%
  filter(term != "(Intercept)")

coef
```

```{r, fig.width=7, fig.height=4.5}
colors <- c( '#C4DDF8', '#4BABED', '#2A6B97', '#183044')

speed_loglog <- coef %>%
  filter(charging_rate > 10) %>%
  ggplot(aes(x=charging_rate, y=estimate, color=factor(speed))) + 
  geom_point(size=2.5) +
  geom_line(linewidth=1) +
  scale_x_continuous(trans="log10", 
                     name="charging rate",
                     breaks=c(10, 30, 100, 300, 1000, 3000, 10000),
                     labels=c("10", "30", "100", "300", "1000", "3000", "10000"),
                     expand = expansion(mult = c(0.1, 0.1))) +
  scale_y_continuous(trans="log10", 
                     name="recoding sensitivity", 
                     limits = c(1e-6, 1e-4),
                     expand = expansion(mult = c(0.05, 0.05))) +
  scale_color_manual(values = colors, name = "speed") +
  #scale_color_manual(values = c("#2A6B97"), name = "speed") +
  #coord_fixed(ratio=1) +
  theme_linedraw() +
  theme(axis.title = element_text(size = 12),
        axis.text = element_text(size = 12),
        legend.title = element_text(size=12),
        panel.background = element_rect(color="grey70"),
        panel.grid.minor.x = element_blank(),
        axis.line = element_line(color="black"),
        axis.ticks = element_blank(),
        legend.position = "None")
```

```{r}
speed_logx <- coef %>%
  filter(charging_rate > 10) %>%
  ggplot(aes(x=charging_rate, y=estimate, color=factor(speed))) + 
  geom_point(size=2.5) +
  geom_line(linewidth=1) +
  scale_x_continuous(trans="log10", 
                     name="charging rate",
                     breaks=c(30, 100, 300, 1000, 3000, 10000),
                     labels=c("30", "100", "300", "1000", "3000", "10000"),
                     expand = expansion(mult = c(0.1, 0.1))) +
  scale_y_continuous( 
                     name="recoding sensitivity", 
                     limits = c(1e-6, 1e-4),
                     expand = expansion(mult = c(0.05, 0.05))) +
  scale_color_manual(values = colors, name = "speed") +
  #scale_color_manual(values = c("#2A6B97"), name = "speed") +
  #coord_fixed(ratio=1) +
  theme_linedraw() +
  theme(axis.title = element_text(size = 12),
        axis.text = element_text(size = 12),
        legend.title = element_text(size=12),
        panel.background = element_rect(color="grey70"),
        panel.grid.minor.x = element_blank(),
        axis.line = element_line(color="black"),
        axis.ticks = element_blank())
```

```{r}
speed_plot <- cowplot::plot_grid(speed_loglog, speed_logx, rel_widths = c(0.33, 0.4))
speed_plot
ggsave("figures/speed_plot.png", width = 10, height = 4)
```
